name: drules
description: A simple rule engine for Dart. It allows you to define rules in Json format and execute them against a given context.
version: 1.0.0
homepage: https://github.com/dizitart/drules
repository: https://github.com/dizitart/drules

environment:
  sdk: ^3.4.1

dependencies:
  async: ^2.11.0
  event_bus: ^2.0.0
  template_expressions: ^3.2.0+9
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.11
  lints: ">=4.0.0 <6.0.0"
  mockito: ^5.4.4
  test: ^1.24.9
